

CREATE TABLE Subject2(
	subjectID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	FullName VARCHAR(200) NOT NULL,
	Age VARCHAR(40) NOT NULL,
	Sex ENUM('M', 'F') NOT NULL,
	Phone VARCHAR(200) NOT NULL,
	Status ENUM('0', '1') NOT NULL
);

CREATE TABLE fagerstrom(
	F_num INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Ans_1 CHAR(2) NOT NULL,
	Ans_2 CHAR(2) NOT NULL,
	Ans_3 CHAR(2) NOT NULL,
	Ans_4 CHAR(2) NOT NULL,
	Ans_5 CHAR(2) NOT NULL,
	Ans_6 CHAR(2) NOT NULL,
	subjectID int(100) NULL
);

CREATE TABLE rosenberg(
	R_num INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Ans_1 CHAR(2) NOT NULL,
	Ans_2 CHAR(2) NOT NULL,
	Ans_3 CHAR(2) NOT NULL,
	Ans_4 CHAR(2) NOT NULL,
	Ans_5 CHAR(2) NOT NULL,
	Ans_6 CHAR(2) NOT NULL,
	Ans_7 CHAR(2) NOT NULL,
	Ans_8 CHAR(2) NOT NULL,
	Ans_9 CHAR(2) NOT NULL,
	Ans_10 CHAR(2) NOT NULL,
	subjectID int(100) NULL
);

CREATE TABLE researcher(
	username VARCHAR(200)NOT NULL,
	password VARCHAR(200) NOT NULL
);

CREATE TABLE tbltemp(
	tempID VARCHAR(2)
);

ALTER TABLE `fagerstrom` ADD CONSTRAINT `fagerstrom_subject_fk` FOREIGN KEY (`subjectID`) 
REFERENCES `epl361_project`.`subject2`(`subjectID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `rosenberg` ADD CONSTRAINT `rosenberg_subject_fk` FOREIGN KEY (`subjectID`) 
REFERENCES `epl361_project`.`subject2`(`subjectID`) ON DELETE RESTRICT ON UPDATE RESTRICT;


